# Generated by Django 4.0.3 on 2022-03-31 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
            ],
            options={
                'verbose_name_plural': '저자',
            },
        ),
        migrations.CreateModel(
            name='Commissioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
            ],
            options={
                'verbose_name_plural': '위원',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('author', models.ManyToManyField(blank=True, related_name='paper_author', to='icasl.author', verbose_name='저자')),
            ],
            options={
                'verbose_name_plural': '논문',
            },
        ),
        migrations.CreateModel(
            name='Session3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_title', models.CharField(max_length=200, verbose_name='세션 주제')),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_chair_session3', to='icasl.commissioner', verbose_name='의장')),
                ('paper', models.ManyToManyField(blank=True, related_name='third_paper_session3', to='icasl.paper', verbose_name='논문')),
            ],
            options={
                'verbose_name_plural': '세션3',
            },
        ),
        migrations.CreateModel(
            name='Session2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_title', models.CharField(max_length=200, verbose_name='세션 주제')),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_chair_session2', to='icasl.commissioner', verbose_name='의장')),
                ('paper', models.ManyToManyField(blank=True, related_name='second_paper_session2', to='icasl.paper', verbose_name='논문')),
            ],
            options={
                'verbose_name_plural': '세션2',
            },
        ),
        migrations.CreateModel(
            name='Session1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_title', models.CharField(max_length=200, verbose_name='세션 주제')),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_chair_session1', to='icasl.commissioner', verbose_name='의장')),
                ('paper', models.ManyToManyField(blank=True, related_name='first_paper_session1', to='icasl.paper', verbose_name='논문')),
            ],
            options={
                'verbose_name_plural': '세션1',
            },
        ),
        migrations.CreateModel(
            name='Keynote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keynote_title', models.CharField(max_length=200, verbose_name='키노트 주제')),
                ('presenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keynote_presenter', to='icasl.author', verbose_name='발표자')),
            ],
            options={
                'verbose_name_plural': '키노트스피치',
            },
        ),
        migrations.CreateModel(
            name='Icasl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateField(verbose_name='일시')),
                ('place', models.CharField(max_length=200, verbose_name='장소')),
                ('advisory', models.ManyToManyField(blank=True, related_name='advisory', to='icasl.commissioner')),
                ('chairman', models.ManyToManyField(blank=True, related_name='chairman', to='icasl.commissioner')),
                ('convenor', models.ManyToManyField(blank=True, related_name='convenor', to='icasl.commissioner')),
                ('coordinators', models.ManyToManyField(blank=True, related_name='coordinators', to='icasl.commissioner')),
                ('keynote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icasl.keynote', verbose_name='키노트')),
                ('secretarles', models.ManyToManyField(blank=True, related_name='secretarles', to='icasl.commissioner')),
                ('session1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icasl.session1', verbose_name='세션1')),
                ('session2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icasl.session2', verbose_name='세션2')),
                ('session3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icasl.session3', verbose_name='세션2')),
                ('staff', models.ManyToManyField(blank=True, related_name='staff', to='icasl.commissioner')),
            ],
        ),
    ]
