# Generated by Django 4.0.3 on 2022-03-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icasl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icasl',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='개최도시'),
        ),
        migrations.AddField(
            model_name='icasl',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='개최국'),
        ),
        migrations.AddField(
            model_name='icasl',
            name='ordinal',
            field=models.CharField(default=1, max_length=200, verbose_name='회차'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='icasl',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='장소'),
        ),
    ]
