# Generated by Django 4.0.3 on 2022-04-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icasl', '0002_icasl_city_icasl_country_icasl_ordinal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icasl',
            options={'verbose_name_plural': 'ICASL'},
        ),
    ]
