# Generated by Django 4.0.4 on 2022-06-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icasl', '0003_alter_icasl_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icasl',
            name='session3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icasl.session3', verbose_name='세션3'),
        ),
        migrations.CreateModel(
            name='Session4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_title', models.CharField(max_length=200, verbose_name='세션 주제')),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forth_chair_session4', to='icasl.commissioner', verbose_name='의장')),
                ('paper', models.ManyToManyField(blank=True, related_name='forth_paper_session4', to='icasl.paper', verbose_name='논문')),
            ],
            options={
                'verbose_name_plural': '세션4',
            },
        ),
        migrations.AddField(
            model_name='icasl',
            name='session4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icasl.session4', verbose_name='세션4'),
        ),
    ]
