# Generated by Django 4.0.4 on 2022-06-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icasl', '0004_alter_icasl_session3_session4_icasl_session4'),
    ]

    operations = [
        migrations.AddField(
            model_name='icasl',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='icasl/post_image/%Y/%m/%d', verbose_name='포스트이미지'),
        ),
    ]
