# Generated by Django 4.0.3 on 2022-03-26 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/cover_image/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=50, verbose_name='작성자')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(null=True, verbose_name='내용')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='변경일')),
                ('top_fixed', models.BooleanField(default=False, verbose_name='상위노출')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.coverimage', verbose_name='커버 이미지')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.image', verbose_name='내용이미지')),
            ],
            options={
                'verbose_name_plural': '학회소식',
            },
        ),
    ]
