# Generated by Django 4.0.3 on 2022-03-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('affiliated', models.CharField(max_length=50, verbose_name='소속')),
            ],
            options={
                'verbose_name_plural': '저자',
            },
        ),
        migrations.CreateModel(
            name='Compete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('award', models.CharField(blank=True, choices=[('best', '최우수상'), ('outstand', '우수상'), ('Encourage', '장려상')], max_length=10, null=True, verbose_name='수상')),
                ('presentation', models.FileField(blank=True, null=True, upload_to='conference/compete/files/%Y/%m/%d')),
                ('author', models.ManyToManyField(blank=True, to='conference.author', verbose_name='저자')),
            ],
            options={
                'verbose_name_plural': '경쟁세션',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='conference/images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Normal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('award', models.CharField(blank=True, choices=[('best', '최우수논문상'), ('outstand', '우수논문상')], max_length=10, null=True, verbose_name='수상')),
                ('presentation', models.FileField(blank=True, null=True, upload_to='conference/normal/files/%Y/%m/%d')),
                ('author', models.ManyToManyField(blank=True, to='conference.author', verbose_name='저자')),
            ],
            options={
                'verbose_name_plural': '일반세션',
            },
        ),
        migrations.CreateModel(
            name='Keynote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('presentation', models.FileField(blank=True, null=True, upload_to='conference/keynote/files/%Y/%m/%d')),
                ('author', models.ManyToManyField(blank=True, to='conference.author', verbose_name='저자')),
            ],
            options={
                'verbose_name_plural': '키노트스피치',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('spring', '춘계'), ('summer', '하계'), ('autumn', '추계'), ('winter', '동계')], max_length=50)),
                ('topic', models.CharField(max_length=200, verbose_name='주제')),
                ('schedule', models.DateField(verbose_name='일시')),
                ('place', models.CharField(max_length=200, verbose_name='장소')),
                ('joint', models.CharField(max_length=200, verbose_name='공동주최')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='conference/cover_image/%Y/%m/%d', verbose_name='커버이미지')),
                ('compete', models.ManyToManyField(blank=True, to='conference.compete', verbose_name='경쟁 세션')),
                ('image', models.ManyToManyField(blank=True, to='conference.image', verbose_name='내용이미지')),
                ('keynote', models.ManyToManyField(blank=True, to='conference.keynote', verbose_name='키노트 스피치')),
                ('normal', models.ManyToManyField(blank=True, to='conference.normal', verbose_name='일반 세션')),
            ],
            options={
                'verbose_name_plural': '학술대회',
            },
        ),
    ]
