# Generated by Django 3.2.9 on 2022-01-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20220125_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='notice',
            name='file',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='image',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='notice',
            name='file_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notice.fileimage'),
        ),
    ]
