# Generated by Django 3.2.9 on 2022-01-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_auto_20220126_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.ManyToManyField(blank=True, to='notice.File'),
        ),
    ]
