# Generated by Django 3.2.9 on 2022-01-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0011_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notice/files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notice/images/%Y/%m/%d'),
        ),
    ]
