# Generated by Django 3.2.9 on 2022-02-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0013_auto_20220202_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='home_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
