# Generated by Django 3.2.9 on 2022-01-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_auto_20220126_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='file',
        ),
        migrations.AddField(
            model_name='notice',
            name='file',
            field=models.ManyToManyField(blank=True, null=True, to='notice.File'),
        ),
    ]
