# Generated by Django 4.0.1 on 2022-01-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0008_alter_notice_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='image',
        ),
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ManyToManyField(blank=True, to='notice.Image'),
        ),
    ]
