# Generated by Django 3.2.9 on 2022-01-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0010_auto_20220126_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/notice/images/%Y/%m/%d'),
        ),
    ]
