# Generated by Django 3.2.9 on 2022-02-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organization',
            new_name='affiliated',
        ),
    ]
